on:
  push:
    branches: [seunghee-test]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: call API
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://15.165.77.33:3000/githubWatcher'
          method: 'POST'
          data: '{"caller": "pushWatcher"}'
