on:
  push:
    branches: [seunghee-test]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Call API
        id: myRequest
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://15.165.77.33:3000/githubWatcher'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"caller": "pushWatcher"}'
