on:
  push:
    branches: [seunghee-test]
jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Call API
        id: myRequest
        uses: fjogeleit/http-request-action@main
        with:
          url: 'http://15.165.77.33:3000/githubWatcher'
          method: 'POST'
          data: '{"name1": "${{ env.BRANCH_NAME }}"}'
      - name: Call API2
        uses: satak/webrequest-action@master
        with:
          url: 'http://15.165.77.33:3000/githubWatcher'
          method: POST
          payload: '{"name2": "${{ github.head_ref }}"}'
