on:
  push:
    branches: [seunghee-test]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: call API
        uses: ./.github/workflows/pushWatcher
        with:
          url: 'https://localhost:3000/githubWatcher'
          method: 'POST'
          data: '{"caller": "pushWatcher"}'
