on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ github.repository }}
      BRANCH: ${{ github.head_ref || github.ref_name }}
      SHA: ${{ github.sha }}
      TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Call API
        id: myRequest
        uses: fjogeleit/http-request-action@main
        with:
          url: 'http://15.165.77.33:3000/githubWatcher'
          method: 'POST'
          data: '{"repository": "${{ env.REPOSITORY }}", "branch": "${{ env.BRANCH }}", "sha":"${{ env.SHA }}", "token": "${{ env.TOKEN }}"}'
